### PR TITLE
Tutorial

### PR DESCRIPTION
**Pull request by satsumas**
A cleaner branch, without test files or CWL files, to be used in conjunction with the docs tutorial.

### CODE REVIEW

**Comment by mattions** [comment]
One question: do you think we can link the Seven Bridges log from some static images from the website, instead of adding a jpg on the repo?

**Comment by satsumas** [comment]
Wasn't entirely sure what you meant -- I added a link to the Seven Bridges website from the jpg, but left it in the repo.

**Comment by mattions** [comment]
Sorry.
I meant link to the hosted one, and then remove the image.

**Comment by satsumas** [comment]
OK, we'll figure out a stable location to host the image later. For now: no image. Thanks 👍

**Pull request merged**
